#!/usr/bin/env python3
"""Generates one GTK4/libadwaita CSS file per colour scheme into ./themes/.

Run this whenever you tweak a palette below:
    python3 build_themes.py

Each generated file overrides libadwaita's *named colors*
(accent_color, window_bg_color, card_bg_color, sidebar_bg_color, ...)
so every built-in widget (headerbar, sidebar, cards, buttons, switches)
automatically follows the scheme -- no per-widget CSS classes needed.

Palette values are the well-known published colours for each project.
Treat them as close, easily-tweakable approximations, not pixel-perfect
ports -- swap any hex below and re-run this script to adjust.
"""
from pathlib import Path

OUT_DIR = Path(__file__).parent / "themes"

TEMPLATE = """/* Auto-generated by build_themes.py -- do not hand-edit, edit the
   palette in build_themes.py instead and re-run it. */

@define-color accent_color {accent};
@define-color accent_bg_color {accent};
@define-color accent_fg_color {accent_fg};

@define-color window_bg_color {bg};
@define-color window_fg_color {fg};

@define-color view_bg_color {bg_alt};
@define-color view_fg_color {fg};

@define-color headerbar_bg_color {bg_alt};
@define-color headerbar_fg_color {fg};
@define-color headerbar_border_color {fg};
@define-color headerbar_backdrop_color {bg};
@define-color headerbar_shade_color {shade};

@define-color card_bg_color {surface};
@define-color card_fg_color {fg};
@define-color card_shade_color {shade};

@define-color dialog_bg_color {bg_alt};
@define-color dialog_fg_color {fg};

@define-color popover_bg_color {surface};
@define-color popover_fg_color {fg};

@define-color sidebar_bg_color {bg};
@define-color sidebar_fg_color {fg};
@define-color sidebar_backdrop_color {bg};
@define-color sidebar_border_color {shade};
@define-color sidebar_shade_color {shade};

@define-color success_color {green};
@define-color success_bg_color {green};
@define-color warning_color {yellow};
@define-color warning_bg_color {yellow};
@define-color error_color {red};
@define-color error_bg_color {red};
@define-color destructive_color {red};
@define-color destructive_bg_color {red};

/* app-specific classes, see style.css */
.anicli-card {{
    background-color: {surface};
    color: {fg};
}}
.anicli-subtitle {{
    color: {muted};
}}
.anicli-pill-sub {{
    background-color: {blue};
    color: {accent_fg};
}}
.anicli-pill-dub {{
    background-color: {accent};
    color: {accent_fg};
}}
"""

# name -> (display name, is_dark, palette dict)
PALETTES = {
    "everforest-dark": ("Everforest (Dark)", True, dict(
        bg="#2d353b", bg_alt="#343f44", surface="#3d484d", fg="#d3c6aa",
        muted="#859289", shade="#232a2e", accent="#a7c080", accent_fg="#2d353b",
        red="#e67e80", green="#a7c080", yellow="#dbbc7f", blue="#7fbbb3")),
    "everforest-light": ("Everforest (Light)", False, dict(
        bg="#fdf6e3", bg_alt="#f4f0d9", surface="#efebd4", fg="#5c6a72",
        muted="#939f91", shade="#e5ddb8", accent="#8da101", accent_fg="#fdf6e3",
        red="#f85552", green="#8da101", yellow="#dfa000", blue="#3a94c5")),

    "tokyonight-dark": ("Tokyo Night (Dark)", True, dict(
        bg="#1a1b26", bg_alt="#16161e", surface="#24283b", fg="#c0caf5",
        muted="#565f89", shade="#101014", accent="#7aa2f7", accent_fg="#1a1b26",
        red="#f7768e", green="#9ece6a", yellow="#e0af68", blue="#7aa2f7")),
    "tokyonight-light": ("Tokyo Night Day (Light)", False, dict(
        bg="#e1e2e7", bg_alt="#d5d6db", surface="#cbccd1", fg="#3760bf",
        muted="#8990b3", shade="#c4c5ca", accent="#2e7de9", accent_fg="#e1e2e7",
        red="#f52a65", green="#587539", yellow="#8c6c3e", blue="#2e7de9")),

    "catppuccin-mocha": ("Catppuccin Mocha (Dark)", True, dict(
        bg="#1e1e2e", bg_alt="#181825", surface="#313244", fg="#cdd6f4",
        muted="#a6adc8", shade="#11111b", accent="#cba6f7", accent_fg="#1e1e2e",
        red="#f38ba8", green="#a6e3a1", yellow="#f9e2af", blue="#89b4fa")),
    "catppuccin-macchiato": ("Catppuccin Macchiato (Dark)", True, dict(
        bg="#24273a", bg_alt="#1e2030", surface="#363a4f", fg="#cad3f5",
        muted="#a5adcb", shade="#181926", accent="#c6a0f6", accent_fg="#24273a",
        red="#ed8796", green="#a6da95", yellow="#eed49f", blue="#8aadf4")),
    "catppuccin-frappe": ("Catppuccin Frappe (Dark)", True, dict(
        bg="#303446", bg_alt="#292c3c", surface="#414559", fg="#c6d0f5",
        muted="#a5adce", shade="#232634", accent="#ca9ee6", accent_fg="#303446",
        red="#e78284", green="#a6d189", yellow="#e5c890", blue="#8caaee")),
    "catppuccin-latte": ("Catppuccin Latte (Light)", False, dict(
        bg="#eff1f5", bg_alt="#e6e9ef", surface="#dce0e8", fg="#4c4f69",
        muted="#8c8fa1", shade="#ccd0da", accent="#8839ef", accent_fg="#eff1f5",
        red="#d20f39", green="#40a02b", yellow="#df8e1d", blue="#1e66f5")),

    "gruvbox-dark": ("Gruvbox (Dark)", True, dict(
        bg="#282828", bg_alt="#1d2021", surface="#3c3836", fg="#ebdbb2",
        muted="#a89984", shade="#1d2021", accent="#d79921", accent_fg="#282828",
        red="#cc241d", green="#98971a", yellow="#d79921", blue="#458588")),
    "gruvbox-light": ("Gruvbox (Light)", False, dict(
        bg="#fbf1c7", bg_alt="#f2e5bc", surface="#ebdbb2", fg="#3c3836",
        muted="#7c6f64", shade="#d5c4a1", accent="#af3a03", accent_fg="#fbf1c7",
        red="#cc241d", green="#79740e", yellow="#b57614", blue="#076678")),

    "nord-dark": ("Nordic / Nord (Dark)", True, dict(
        bg="#2e3440", bg_alt="#272c36", surface="#3b4252", fg="#eceff4",
        muted="#8b94a8", shade="#22262e", accent="#88c0d0", accent_fg="#2e3440",
        red="#bf616a", green="#a3be8c", yellow="#ebcb8b", blue="#81a1c1")),
    "nord-light": ("Nordic / Nord (Light)", False, dict(
        bg="#eceff4", bg_alt="#e5e9f0", surface="#d8dee9", fg="#2e3440",
        muted="#4c566a", shade="#c9d0dd", accent="#5e81ac", accent_fg="#eceff4",
        red="#bf616a", green="#4c8a5e", yellow="#a98600", blue="#5e81ac")),

    "dracula": ("Dracula (Dark)", True, dict(
        bg="#282a36", bg_alt="#21222c", surface="#44475a", fg="#f8f8f2",
        muted="#6272a4", shade="#191a21", accent="#bd93f9", accent_fg="#282a36",
        red="#ff5555", green="#50fa7b", yellow="#f1fa8c", blue="#8be9fd")),

    "solarized-dark": ("Solarized (Dark)", True, dict(
        bg="#002b36", bg_alt="#00212b", surface="#073642", fg="#93a1a1",
        muted="#586e75", shade="#001b22", accent="#268bd2", accent_fg="#002b36",
        red="#dc322f", green="#859900", yellow="#b58900", blue="#268bd2")),
    "solarized-light": ("Solarized (Light)", False, dict(
        bg="#fdf6e3", bg_alt="#eee8d5", surface="#e9e2cb", fg="#657b83",
        muted="#93a1a1", shade="#d8d2ba", accent="#268bd2", accent_fg="#fdf6e3",
        red="#dc322f", green="#859900", yellow="#b58900", blue="#268bd2")),

    "rosepine-main": ("Rose Pine (Dark)", True, dict(
        bg="#191724", bg_alt="#16141f", surface="#1f1d2e", fg="#e0def4",
        muted="#908caa", shade="#0f0e17", accent="#c4a7e7", accent_fg="#191724",
        red="#eb6f92", green="#31748f", yellow="#f6c177", blue="#9ccfd8")),
    "rosepine-dawn": ("Rose Pine Dawn (Light)", False, dict(
        bg="#faf4ed", bg_alt="#fffaf3", surface="#f2e9e1", fg="#575279",
        muted="#9893a5", shade="#e5ddd3", accent="#907aa9", accent_fg="#faf4ed",
        red="#b4637a", green="#286983", yellow="#ea9d34", blue="#56949f")),

    "kanagawa": ("Kanagawa (Dark)", True, dict(
        bg="#1f1f28", bg_alt="#16161d", surface="#2a2a37", fg="#dcd7ba",
        muted="#727169", shade="#0d0d12", accent="#7fb4ca", accent_fg="#1f1f28",
        red="#c34043", green="#76946a", yellow="#dca561", blue="#7fb4ca")),
}


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for theme_id, (_name, _dark, palette) in PALETTES.items():
        css = TEMPLATE.format(**palette)
        (OUT_DIR / f"{theme_id}.css").write_text(css, encoding="utf-8")
        print(f"wrote {theme_id}.css")


if __name__ == "__main__":
    main()
